services:
  dmarc-report-visualizer:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./data/inbox:/data/inbox
      - ./data/reports:/data/reports
    environment:
      SCAN_INTERVAL_SECONDS: 30
      REPORT_RETENTION_MONTHS: 0
