services:
  dmarc-report-visualizer:
    build:
      context: .
      target: ${DOCKER_TARGET:-runtime-apache}
    container_name: dmarc-report-visualizer
    ports:
      - "8090:80"
    volumes:
      - ./data/inbox:/data/inbox
      - ./data/reports:/data/reports
    environment:
      SCAN_INTERVAL_SECONDS: 30
      REPORT_RETENTION_MONTHS: 0
